name: ESLint

on: push

jobs:
  release:
    name: ESLint
    runs-on: ubuntu-latest
    container: 'node:lts-buster'
    steps:
      - uses: actions/checkout@v2
      - run: cd client/
      - run: ls -a
      - run: yarn --frozen-lockfile
      - run: yarn lint