name: ESLint

on: push

jobs:
  release:
    name: ESLint
    runs-on: ubuntu-latest
    container: 'node:lts-buster'
    steps:
      - uses: actions/checkout@v2
      - run: cd client && yarn --frozen-lockfile && yarn lint